/**
 * 50 mock Toronto bars for local / demo seeding (exactly 50 entries).
 * Coordinates are approximate real neighbourhood anchors.
 */

export type SeedBar = {
  name: string;
  lat: number;
  lng: number;
  is_streaming_wc: boolean;
  entry_type: "Walk-in" | "Reservation" | "Ticketed";
  cover_charge: string;
  fan_hub: string;
  vibe_notes: string;
  audio_status: "Full Audio" | "Visual Only";
};

export const SEED_BARS: SeedBar[] = [
  {
    name: "The Football Factory",
    lat: 43.6487,
    lng: -79.4025,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "England",
    vibe_notes:
      "Loud, packed, proper pub atmosphere. Arrive 30 min before kickoff for a seat near the main screen.",
    audio_status: "Full Audio",
  },
  {
    name: "Liberty Village Sports Bar",
    lat: 43.638,
    lng: -79.4194,
    is_streaming_wc: true,
    entry_type: "Reservation",
    cover_charge: "$10",
    fan_hub: "Croatia",
    vibe_notes:
      "Croatia fan hub energy every match day. Book ahead for knockout rounds.",
    audio_status: "Full Audio",
  },
  {
    name: "Harbourfront Watch Party",
    lat: 43.6394,
    lng: -79.3806,
    is_streaming_wc: true,
    entry_type: "Ticketed",
    cover_charge: "$15",
    fan_hub: "None",
    vibe_notes:
      "Outdoor patio screens with lake views. Ticket includes one drink; audio is limited on the patio.",
    audio_status: "Visual Only",
  },
  {
    name: "Maple Leaf Tavern",
    lat: 43.6532,
    lng: -79.3832,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "Canada",
    vibe_notes: "Neighbourhood dive with three TVs and zero pretension. Great for casual group watches.",
    audio_status: "Full Audio",
  },
  {
    name: "King Street Supporters Club",
    lat: 43.6448,
    lng: -79.3951,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "$5",
    fan_hub: "Brazil",
    vibe_notes: "Samba drums optional. Standing room fills fast when Brazil plays — come early.",
    audio_status: "Full Audio",
  },
  {
    name: "Queen West Pitch & Pint",
    lat: 43.6431,
    lng: -79.4187,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "None",
    vibe_notes: "Indie crowd, craft taps, one massive projector wall. Chill vibes for afternoon matches.",
    audio_status: "Full Audio",
  },
  {
    name: "Distillery District Screen House",
    lat: 43.6503,
    lng: -79.3596,
    is_streaming_wc: true,
    entry_type: "Reservation",
    cover_charge: "$10",
    fan_hub: "Italy",
    vibe_notes: "Cobblestone courtyard screens in summer. Azzurri flags everywhere when Italy is on.",
    audio_status: "Visual Only",
  },
  {
    name: "St. Lawrence Market Pub",
    lat: 43.6489,
    lng: -79.3717,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "None",
    vibe_notes: "Post-market crowd mixes with football fans. Fish and chips pair well with noon kickoffs.",
    audio_status: "Full Audio",
  },
  {
    name: "Yorkville Sports Lounge",
    lat: 43.6709,
    lng: -79.3925,
    is_streaming_wc: true,
    entry_type: "Reservation",
    cover_charge: "$20",
    fan_hub: "France",
    vibe_notes: "Upscale lounge with table service. Dress code casual-smart on weekend nights.",
    audio_status: "Full Audio",
  },
  {
    name: "Danforth Greek & Goals",
    lat: 43.6764,
    lng: -79.352,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "Greece",
    vibe_notes: "Greek street food and passionate debates. Plates smashing metaphorically only.",
    audio_status: "Full Audio",
  },
  {
    name: "Leslieville Rovers Den",
    lat: 43.6623,
    lng: -79.3289,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "$5",
    fan_hub: "England",
    vibe_notes: "Family-friendly early games; turns into a proper pub after 9pm. Dog-friendly patio.",
    audio_status: "Full Audio",
  },
  {
    name: "Kensington Scorers Cellar",
    lat: 43.6547,
    lng: -79.4002,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "Mexico",
    vibe_notes: "Tight basement bar, incredible energy for El Tri matches. Spicy micheladas on tap.",
    audio_status: "Full Audio",
  },
  {
    name: "Annex Academics Athletic Club",
    lat: 43.6672,
    lng: -79.4068,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "None",
    vibe_notes: "Student-heavy, cheap pints, tactical discussions at half-time. Quieter for group stage noon games.",
    audio_status: "Full Audio",
  },
  {
    name: "College Street Ultras Bar",
    lat: 43.6561,
    lng: -79.4095,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "$5",
    fan_hub: "Argentina",
    vibe_notes: "Messi jerseys everywhere. Expect singing, drums, and zero personal space on big nights.",
    audio_status: "Full Audio",
  },
  {
    name: "Parkdale Pitch House",
    lat: 43.6392,
    lng: -79.4401,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "None",
    vibe_notes: "West-end locals spot. Rotating food pop-up in the beer garden out back.",
    audio_status: "Full Audio",
  },
  {
    name: "Junction Triangle Taproom",
    lat: 43.6654,
    lng: -79.4703,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "Germany",
    vibe_notes: "Craft beer focus with German lagers featured during Die Mannschaft matches.",
    audio_status: "Full Audio",
  },
  {
    name: "Bloor-Yonge Central Sports",
    lat: 43.6703,
    lng: -79.386,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "$10",
    fan_hub: "None",
    vibe_notes: "Dozens of screens on two floors. Tourist-friendly but genuinely good sightlines.",
    audio_status: "Full Audio",
  },
  {
    name: "Entertainment District Mega Screen",
    lat: 43.6465,
    lng: -79.3892,
    is_streaming_wc: true,
    entry_type: "Ticketed",
    cover_charge: "$15",
    fan_hub: "None",
    vibe_notes: "Stadium-style LED wall. Ticketed for marquee matches only; walk-in for group stage.",
    audio_status: "Full Audio",
  },
  {
    name: "Front Street Financial Fans",
    lat: 43.6478,
    lng: -79.3815,
    is_streaming_wc: true,
    entry_type: "Reservation",
    cover_charge: "$10",
    fan_hub: "USA",
    vibe_notes: "After-work crowd in suits loosening ties. USA games feel like a office party here.",
    audio_status: "Full Audio",
  },
  {
    name: "Union Station Transit Tavern",
    lat: 43.6453,
    lng: -79.3806,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "None",
    vibe_notes: "Perfect for catching a half before your GO train. Quick service, loud when commutes overlap with games.",
    audio_status: "Visual Only",
  },
  {
    name: "Cabbagetown Corner Kick",
    lat: 43.6678,
    lng: -79.3689,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "Scotland",
    vibe_notes: "Small but mighty. Tartan bunting up year-round. Whisky specials at halftime.",
    audio_status: "Full Audio",
  },
  {
    name: "Riverdale Riverside Pub",
    lat: 43.6612,
    lng: -79.351,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "None",
    vibe_notes: "Balcony overlooks the valley. Best for sunset kickoffs with a breeze.",
    audio_status: "Visual Only",
  },
  {
    name: "Beaches Boardwalk Bar",
    lat: 43.6714,
    lng: -79.2945,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "$5",
    fan_hub: "Spain",
    vibe_notes: "La Roja supporters pack the patio. Sandy feet welcome from a pre-game swim.",
    audio_status: "Visual Only",
  },
  {
    name: "Roncesvalles Polonia Pub",
    lat: 43.6521,
    lng: -79.4492,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "Poland",
    vibe_notes: "Pierogies and passionate Polish chants. Community feel on every match day.",
    audio_status: "Full Audio",
  },
  {
    name: "High Park Highland House",
    lat: 43.6468,
    lng: -79.4645,
    is_streaming_wc: true,
    entry_type: "Reservation",
    cover_charge: "$10",
    fan_hub: "None",
    vibe_notes: "Fireplace indoors, picnic tables out back. Reserve for weekend quarter-finals.",
    audio_status: "Full Audio",
  },
  {
    name: "Etobicoke Lakeshore Legends",
    lat: 43.6205,
    lng: -79.4942,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "Portugal",
    vibe_notes: "West-end drive-in crowd. Ample parking and a big parking-lot screen in summer.",
    audio_status: "Full Audio",
  },
  {
    name: "North York Centre Sports Grill",
    lat: 43.7614,
    lng: -79.4132,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "$5",
    fan_hub: "South Korea",
    vibe_notes: "K-pop halftime playlists and soju shots when Korea plays. Surprisingly rowdy.",
    audio_status: "Full Audio",
  },
  {
    name: "Scarborough Bluffs View Bar",
    lat: 43.7098,
    lng: -79.2587,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "None",
    vibe_notes: "East-end gem with cliff views. Worth the trek for knockout matches.",
    audio_status: "Full Audio",
  },
  {
    name: "Markham Road International Pub",
    lat: 43.7732,
    lng: -79.2641,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "Japan",
    vibe_notes: "Japanese expat crowd for Samurai Blue games. Ramen bar open late.",
    audio_status: "Full Audio",
  },
  {
    name: "Mississauga Border Sports Hub",
    lat: 43.5891,
    lng: -79.6442,
    is_streaming_wc: true,
    entry_type: "Reservation",
    cover_charge: "$10",
    fan_hub: "None",
    vibe_notes: "Huge suburban space with free parking. Great for big groups from the 905.",
    audio_status: "Full Audio",
  },
  {
    name: "Liberty North Cantina",
    lat: 43.6412,
    lng: -79.4245,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "$5",
    fan_hub: "Mexico",
    vibe_notes: "Tacos and tequila specials. Vibrant whenever CONCACAF neighbours play.",
    audio_status: "Full Audio",
  },
  {
    name: "Fort York Garrison Grill",
    lat: 43.6378,
    lng: -79.4042,
    is_streaming_wc: true,
    entry_type: "Ticketed",
    cover_charge: "$20",
    fan_hub: "None",
    vibe_notes: "Historic venue with outdoor big screen. Premium tickets for final-watch parties.",
    audio_status: "Full Audio",
  },
  {
    name: "CityPlace Sky Lounge",
    lat: 43.6415,
    lng: -79.395,
    is_streaming_wc: true,
    entry_type: "Reservation",
    cover_charge: "$15",
    fan_hub: "None",
    vibe_notes: "High-rise condo crowd rooftop. Wind can drown audio — visuals are the draw.",
    audio_status: "Visual Only",
  },
  {
    name: "Ossington Strip Offside",
    lat: 43.6498,
    lng: -79.4223,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "Netherlands",
    vibe_notes: "Orange jerseys and cycling fans. Dutch courage encouraged, not required.",
    audio_status: "Full Audio",
  },
  {
    name: "Dundas West Derby Day",
    lat: 43.6512,
    lng: -79.4345,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "Belgium",
    vibe_notes: "Waffles at brunch, beer at night. Compact space — expect a line at the door.",
    audio_status: "Full Audio",
  },
  {
    name: "Chinatown Dragon Sports",
    lat: 43.6524,
    lng: -79.3978,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "None",
    vibe_notes: "Dim sum by day, football by night. Late kitchen for West Coast kickoffs.",
    audio_status: "Full Audio",
  },
  {
    name: "Greektown Plateia Pub",
    lat: 43.6789,
    lng: -79.3485,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "$5",
    fan_hub: "Greece",
    vibe_notes: "Outdoor plaza TV in summer. Ouzo shots when Greece scores — mandatory tradition.",
    audio_status: "Visual Only",
  },
  {
    name: "Little Italy Forza Lounge",
    lat: 43.6551,
    lng: -79.4123,
    is_streaming_wc: true,
    entry_type: "Reservation",
    cover_charge: "$10",
    fan_hub: "Italy",
    vibe_notes: "Nonna-approved pasta specials. Azzurri games feel like a family reunion.",
    audio_status: "Full Audio",
  },
  {
    name: "Portugal Village Adega",
    lat: 43.6428,
    lng: -79.4312,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "Portugal",
    vibe_notes: "Grilled sardines and Cristiano chants. Emotional rollercoaster every match.",
    audio_status: "Full Audio",
  },
  {
    name: "Corso Italia Azzurri Club",
    lat: 43.6782,
    lng: -79.4389,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "$5",
    fan_hub: "Italy",
    vibe_notes: "Second-gen Italian-Canadian hub. Espresso machines pause for penalties only.",
    audio_status: "Full Audio",
  },
  {
    name: "Rosedale Members Viewing Room",
    lat: 43.6823,
    lng: -79.3789,
    is_streaming_wc: true,
    entry_type: "Reservation",
    cover_charge: "$20",
    fan_hub: "None",
    vibe_notes: "Members-only feel but walk-ins accepted with reservation. Leather chairs and quiet commentary option.",
    audio_status: "Full Audio",
  },
  {
    name: "Moss Park Community Pitch",
    lat: 43.6589,
    lng: -79.3745,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "None",
    vibe_notes: "Grassroots community vibe. Proceeds from pint sales go to local youth soccer.",
    audio_status: "Full Audio",
  },
  {
    name: "Regent Park Rising Stars",
    lat: 43.6601,
    lng: -79.3623,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "None",
    vibe_notes: "Youth coaches host watch parties. Inspiring atmosphere for families.",
    audio_status: "Full Audio",
  },
  {
    name: "Waterfront Pier 27 Pavilion",
    lat: 43.6402,
    lng: -79.3698,
    is_streaming_wc: true,
    entry_type: "Ticketed",
    cover_charge: "$15",
    fan_hub: "None",
    vibe_notes: "Lake breeze and multiple outdoor screens. Bring a jacket for evening games.",
    audio_status: "Visual Only",
  },
  {
    name: "Canary District Corner Pub",
    lat: 43.6508,
    lng: -79.3542,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "$5",
    fan_hub: "None",
    vibe_notes: "Post-athletes-village neighbourhood bar. Modern interior, classic pub heart.",
    audio_status: "Full Audio",
  },
  {
    name: "Exhibition Place Fairgrounds Bar",
    lat: 43.6321,
    lng: -79.4215,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "$10",
    fan_hub: "None",
    vibe_notes: "Massive capacity for festival-style watch parties. Parking $10 on event days.",
    audio_status: "Full Audio",
  },
  {
    name: "Davisville Midtown Tavern",
    lat: 43.6982,
    lng: -79.3978,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "Switzerland",
    vibe_notes: "Neutral-watch friendly with Swiss chocolate at the bar. Calm, analytical crowd.",
    audio_status: "Full Audio",
  },
  {
    name: "Mount Pleasant Village Pub",
    lat: 43.7045,
    lng: -79.3889,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "No Cover",
    fan_hub: "None",
    vibe_notes: "Upscale midtown locals. Fireplace nook for winter tournaments.",
    audio_status: "Full Audio",
  },
  {
    name: "Yonge & Eglinton Skybox",
    lat: 43.7068,
    lng: -79.3987,
    is_streaming_wc: true,
    entry_type: "Reservation",
    cover_charge: "$10",
    fan_hub: "None",
    vibe_notes: "Midtown office crowd hub. Happy hour overlaps with European evening games.",
    audio_status: "Full Audio",
  },
  {
    name: "St. Clair West Trattoria TV",
    lat: 43.6812,
    lng: -79.4201,
    is_streaming_wc: true,
    entry_type: "Walk-in",
    cover_charge: "$5",
    fan_hub: "Italy",
    vibe_notes: "Homemade pasta and Azzurri flags in the window. Cozy for rainy day matches.",
    audio_status: "Full Audio",
  },
];
